hdfs:
  image: sequenceiq/hadoop-docker:2.4.1
  command: /etc/bootstrap.sh -d -bash

mazerunner:
  image: kbastani/neo4j-graph-analytics:latest
  links:
   - hdfs

graphdb_data:
    image: busybox
    volumes:
        - /opt/data
    command: /bin/sh


graphdb:
  image: kbastani/docker-neo4j:latest
  ports:
   - "7474:7474"
   - "1337:1337"
  volumes_from:
   - graphdb_data
  links:
   - mazerunner
   - hdfs

postgres_data:
    image: busybox
    volumes:
        - /var/lib/postgres
    command: /bin/sh

postgres:
    image: postgres:9.4
    volumes_from:
        - postgres_data
    env_file: .env
    expose:
        - "5432"

uwsgi:
    build: .
    restart: always
    volumes:
        - .:/code
        - /var/www/static
    links:
        - postgres
        - graphdb
    env_file: .env
    command: /code/uwsgi.sh
    expose:
        - "4000"
    working_dir: /code

nginx:
    image: nginx:latest
    volumes_from:
        - uwsgi
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    links:
        - uwsgi
    ports:
        - "0.0.0.0:80:80"
